import { ProfileData, ThemeConfig } from '../contexts/PortfolioContext';
import { Project, skillCategories, experiences, mockEndpoints } from '../data/portfolioData';

export interface PublishedPayload {
  version: string;
  publishedAt: string;
  profile: ProfileData;
  themeConfig: ThemeConfig;
  projects: Project[];
}

export const generatePublishedJson = (
  profile: ProfileData,
  themeConfig: ThemeConfig,
  projects: Project[]
): string => {
  const payload: PublishedPayload = {
    version: '2.0',
    publishedAt: new Date().toISOString(),
    profile,
    themeConfig,
    projects,
  };
  return JSON.stringify(payload, null, 2);
};

export const generatePortfolioDataTs = (
  profile: ProfileData,
  projects: Project[]
): string => {
  const dateStr = new Date().toISOString().split('T')[0];
  return `// ─── Portfolio Data Layer ─────────────────────────────────────────────────────
// Generated by Kibrom's Portfolio Studio on ${dateStr}
// Auto-published configuration for pure, high-performance static rendering.

export const profile = ${JSON.stringify(profile, null, 2)};

export const skillCategories = ${JSON.stringify(skillCategories, null, 2)};

export type Project = {
  id: string;
  title: string;
  tagline: string;
  category: string;
  featured: boolean;
  timeline: string;
  techStack: string[];
  metrics: { label: string; value: string; description: string }[];
  problemStatement: string;
  architectureDescription: string;
  tradeoffs: { decision: string; chosen: string; rejected: string; rationale: string }[];
  role: string;
  liveUrl?: string;
  githubUrl?: string;
  apiEndpoint?: { method: string; path: string; description: string; response: object };
  accentColor: string;
};

export const projects: Project[] = ${JSON.stringify(projects, null, 2)};

export type Experience = {
  id: string;
  role: string;
  organization: string;
  location: string;
  category: 'leadership' | 'engineering' | 'academic';
  startDate: string;
  endDate: string | null;
  isCurrent: boolean;
  summary: string;
  accomplishments: string[];
  technologies?: string[];
  leadershipScope?: string;
};

export const experiences: Experience[] = ${JSON.stringify(experiences, null, 2)};

export const mockEndpoints = ${JSON.stringify(mockEndpoints, null, 2)};
`;
};

export const triggerFileDownload = (content: string, filename: string, mimeType: string = 'application/json') => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
